lerna.json
package.json
yarn.lock

bedrock이 빌드시 오류가 발생합니다.
우선 bedrock 빌드는 제거하고 나중에 optimism에서 해결되면 다시 복구하겠습니다.

[OR-227] remove bedrock from workspace of package

---

.github/workflows/node-packages.yml

Package쪽에 만지다 보니까 lint에서 오류가 나네요.. ㅜ
나중에 bedrock 복구되면 다시 해야겠습니다.

[OR-227] remove check lint

---

package.json

Version 넘버링합니다.
해당 버전으로 release 할 예정입니다.

[OR-336] tokamak-optimism bump version to 0.1.0

---

.github/workflows/tokamak-public-release.yml

Action에서 release할때에 오류가 있어서 수정합니다~
package들 몇개의 path가 틀려졌네요~

[OR-343] Fix version file path on release

---

.github/workflows/tokamak-public-release.yml

[OR-343] Fix version file path of deployer

---

.github/workflows/tokamak-public-nightly.yml

Nightly Build할때에도 git_sha 테그 추가하도록 했습니다.

[OR-344] add gitsha to nightly build

---

l2geth/cmd/utils/flags.go
l2geth/metrics/prometheus/prometheus.go

- set to enable prometheus
- how can I edit l2geth? (Do I make a tokamak/l2geth?)
Thank you!

[OR-309] set to enable prometheus

---

ops/docker-compose.yml
packages/sdk/package.json
packages/tokamak/message-relayer/package.json
packages/tokamak/message-relayer/src/service.ts
yarn.lock

1. package version: v0.5.16 -> v0.5.4
2. relayer service URL 환경 변수 추가
3. tokamak/message-relayer 코드 롤백: L1에 배포된 address manager 주소를 환경 변수로 받아서 처리

[OR-345] rollback tokamak/message-relayer

---

l2geth/cmd/geth/main.go
l2geth/cmd/utils/flags.go

- add flag for metric port
Thank you

[OR-363] add flag for metric port

---

.github/workflows/tokamak-public-nightly.yml

container image push할때에 nightly-XXXX  과 같이 버전도 함께 올리도록 했습니다.

[OR-365] add nightly version

---

packages/tokamak/message-relayer/package.json
packages/tokamak/message-relayer/src/service.ts

Or 371 bug tokamak message relayer

---

ops/docker-compose.yml
ops/docker/Dockerfile.packages
ops/scripts/relayer-fast.sh

fast_relayer 서비스를 ops에 추가
```
git checkout OR-459_add-fast-relayer-service
yarn && yarn build
cd ops
docker-compose up -d
```
https://onther.atlassian.net/browse/OR-459

OR-459 add fast relayer service

---

ops/docker-compose.yml
ops/scripts/relayer-fast.sh
packages/tokamak/message-relayer/.env.example
packages/tokamak/message-relayer/src/service.ts

relayer와 fast relayer를 msg.target으로 구분하여 릴레이 로직을 다르게 탈 수 있도록 필터 생성 및 적용
log를 확인하여 _getFilter()에 의해 적용된 필터가 제대로 생성되었는지 체크
- 0x610178dA211FEF7D417bC0e6FeD39F05609AD788: 출금 msg.target 컨트랙트 주소
- 0xE6E340D132b5f46d1e472DebcD681B2aBc16e57E: 빠른 출금 msg.target 컨트랙트 주소
```bash
{"level":30,"time":1674114525348,"relayerFilterSelect":["0x610178dA211FEF7D417bC0e6FeD39F05609AD788"],"fastRelayerFilterSelect":["0xE6E340D132b5f46d1e472DebcD681B2aBc16e57E"],"msg":"Found the two filters"}
```
```bash
git checkout OR-464_get-filter
yarn && yarn build
cd ops && docker-compose up -d
docker logs -f <CONTAINER_ID_MESSAGE_RELAYER_FAST>
docker logs -f <CONTAINER_ID_MESSAGE_RELAYER>
```
```bash
cd packages/tokamak/message-relayer
cp .env.example .env
yarn && yarn build
yarn start
``` …

OR-464 get filter

---

ops/docker-compose.yml
packages/contracts/contracts/L1/messaging/IL1CrossDomainMessenger.sol
packages/contracts/contracts/L1/messaging/L1CrossDomainMessenger.sol
packages/contracts/docs/IL1CrossDomainMessenger.md
packages/contracts/docs/L1CrossDomainMessenger.md
packages/tokamak/contracts/bin/pass-deploy-params.ts
packages/tokamak/contracts/contracts/L1CrossDomainMessengerFast.sol
packages/tokamak/contracts/deploy/000-L1MessengerFast.deploy.ts
packages/tokamak/message-relayer/package.json
packages/tokamak/message-relayer/src/service.ts

batch-relay를 위한 컨트랙트 내 batchRelayMessages 함수 추가 (fba9d9faae07f1010ec9d10e79e00e1e9e88ead4)
L1-L2 간 relay되는 message를 batch로 전송하기 위한 buffer 생성 (f854e446460a4aed52c5304004edd7fe8f3c56be)
- buffer는 size가 가득 차거나 대기 시간을 초과하면 flush
- 기본값
- buffer size = 2
- timeout = 60
log를 확인하여 현재 buffer 상태와 flush 조건을 확인 
```bash
***********************************
Seconds elapsed since last batch push: 0
Buffer still too small - current buffer length:  0
Buffer flush size set to:  2
***********************************
```
```bash
git checkout OR-474_make-batch
yarn && yarn build
cd ops && docker-compose up -d
docker logs -f <CONTAINER_ID_MESSAGE_RELAYER_FAST>
docker logs -f <CONTAINER_ID_MESSAGE_RELAYER>
```
```bash
cd packages/tokamak/message-relayer
cp .env.example .env
yarn && yarn build
yarn start
``` …

Or 474 make batch

---

packages/sdk/src/cross-chain-messenger.ts
packages/tokamak/message-relayer/package.json
packages/tokamak/message-relayer/src/service.ts
yarn.lock

릴레이할 메시지를 배열로 받아서 L1CrossDomainMessenger.batchRelayMessages와 L1CrossDomainMessengerFast.batchRelayMessages를 호출하여 L1에서 finalize 하는 기능 구현 
(finalizeBatchMessage in sdk)
기능 테스트는 기본 기능 구현 이후 integration-tests에 추가할 예정입니다.
https://onther.atlassian.net/browse/OR-476

Or 476 finalize message

---

batch-submitter/config.go
batch-submitter/drivers/proposer/driver.go

fix flag name for MaxStateRootElements in batch_submitter
fix log package for proposer

OR-542 fix flag name for MaxStateRootElements and log package for proposer

---

integration-tests/test/batch-relayer-fast.spec.ts
integration-tests/test/batch-relayer.spec.ts
integration-tests/test/shared/env.ts
packages/contracts/contracts/L1/messaging/L1CrossDomainMessengerFast.sol
packages/sdk/src/cross-chain-messenger.ts
packages/tokamak/contracts/contracts/L1CrossDomainMessengerFast.sol
packages/tokamak/message-relayer/src/service.ts

relayer의 batch-relay 기능 확인을 위한 테스트 코드 추가
```bash
git checkout OR-543_relayer-batch-test
yarn && yarn build 
cd ops
docker-compose up -d
cd ../integration-tests
yarn test:integration
```
https://onther.atlassian.net/browse/OR-543

Or 543 relayer batch test

---

integration-tests/test/batch-relayer-fast.spec.ts
integration-tests/test/batch-relayer.spec.ts
packages/sdk/src/cross-chain-messenger.ts
packages/tokamak/contracts/README.md
packages/tokamak/message-relayer/.env.example
packages/tokamak/message-relayer/README.md
packages/tokamak/message-relayer/src/service.ts

- Clean up your code
- modify README.md
- add comment in function
```bash
git checkout OR-551_code-cleaning
yarn && yarn build 
cd ops
docker-compose up -d
cd ../integration-tests
yarn test:integration
```
https://onther.atlassian.net/browse/OR-551

[OR-551] chore: clean code and modify README.md

---

.github/workflows/tokamak-public-nightly.yml

Nightly Image는 Build시 linux/arm64도 함께 빌드하도록 합니다~

[OR-586] Support multi-platform for nightly images

---

.github/workflows/tokamak-public-nightly.yml

packages들은 multi platform build가 안되네요..

[OR-586] packages should be built only linux/amd64

---

.github/workflows/tokamak-public-nightly.yml
.github/workflows/tokamak-public-release.yml

deployment를 위해서 tag 업데이트 추가했습니다.
ci/cd부분이라 바로 머지할께요.

[OR-592] Add proxyd deployment

---

proxyd/backend.go
proxyd/proxyd.go

[OR-589] Fixed to check bachendOverCapacity

---

ops/docker-compose.yml
ops/docker/Dockerfile.packages

tokamak relayer들은 같은 container를 사용하도록 했습니다.
테스트는 완료했습니다.

[OR-617] relayers use same container

---

packages/tokamak/message-relayer/package.json
packages/tokamak/message-relayer/src/service.ts

message relayer에서 불필요하게 많이 출력되는 log의 레벨을 info > debug로 조정하였습니다.

change log level in message relayer

---

packages/tokamak/message-relayer/src/service.ts

fix the bug: modify if/else condition to check status of the tx receipt

[OR-670] bugfix: modify to check status of the tx receipt

---

packages/contracts/deploy-config/mainnet.ts

I removed unnecessary deployment files.
and add `ovmFastRelayer` to deploy contracts.

Or 679 mainnet deployment

---

.github/workflows/tokamak-public-release.yml

update mainnet infra image version by release.

[OR-718] update mainnet infra manifest file

---

.github/workflows/tokamak-public-nightly.yml
.github/workflows/tokamak-public-release.yml

Update gas-oracle image tags after nightly/release build.

Or 729 gas oracle ci

---

.github/workflows/tokamak-public-nightly.yml
.github/workflows/tokamak-public-release.yml
integration-tests/package.json
integration-tests/test/shared/env.ts
ops/docker-compose.yml
ops/docker/Dockerfile.packages
package.json
packages/tokamak/message-relayer/README.md
packages/tokamak/message-relayer/package.json
packages/tokamak/message-relayer/src/service.ts
packages/tokamak/sdk/package.json

Change package names for titan.
And the packages should build to container images with changed names.

Or 790 change repo name

---

batch-submitter/package.json
package.json
packages/message-relayer/package.json
proxyd/package.json
proxyd/server.go

- enable cross domain ws connection. (if we use proxyd, it can't connect through browser)
I tested this PR using [rlgns9999/proxyd](https://hub.docker.com/r/rlgns9999/proxyd).

[OR-833] enable cross domain ws connection

---

packages/tokamak/message-relayer/package.json
packages/tokamak/message-relayer/src/service.ts

- I uncommented the `this.metrics.highestKnownL2Tx.set` function to resolve that grafana pannel shows minus number.
Thank you.

[OR-834] fix metrics (highestKnownL2Tx)

---

.github/workflows/tokamak-public-nightly.yml
.github/workflows/tokamak-public-release.yml

tokamak-optimism-infra will be changed to tokamak-titan-infra.

[OR-796] change repo tokamak-optimism-infra to tokamak-titan-infra

---

packages/tokamak/message-relayer/package.json
packages/tokamak/message-relayer/src/service.ts

- fix to set metric normally
- add set metric logic
I'm sorry not to check in the past PR. I checked only the value is set(not 0).
Thank you!

[OR-868] fix to set metric normally

---

packages/tokamak/contracts/README.md
packages/tokamak/contracts/package.json
packages/tokamak/sdk/README.md
packages/tokamak/sdk/package.json
yarn.lock

* change readme & package.json in titan packages
* bump version

Or 799 modify readme titan packages

---

integration-tests/package.json
packages/tokamak/message-relayer/package.json
packages/tokamak/message-relayer/src/service.ts
packages/tokamak/sdk/package.json
yarn.lock

- add metric for relayer balance
Thank you

Or 928 add metric for relayer balance

---

packages/tokamak/message-relayer/package.json

Bump relayer version

---

packages/tokamak/message-relayer/src/service.ts

- change metric name
Thank you

[OR-928] change metric name

---

package.json

- bump version for upgrade
I will merge directly for upgrade. (team member NA)

[OR-924] Bump Version

---

.github/workflows/tokamak-public-nightly.yml
packages/tokamak/contracts/hardhat.config.ts

- Fix solc compiler problem
- Setup template image and private network for runners
- Update docker build flow
- Test: Make a simple cluster on arm based cpu and test by using https://github.com/tokamak-network/tokamak-titan-example/tree/main/standard-bridge-eth

Or 1037 make GitHub action for arm architecture tokamak titan

---

.github/workflows/tokamak-public-nightly.yml

- fix missing dependencies when update kustomize

fix missing dependency

---

batch-submitter/package.json
gas-oracle/package.json
l2geth/package.json
packages/data-transport-layer/package.json
packages/tokamak/message-relayer/package.json
proxyd/package.json

- bump version to check new images
Thank you!

[OR-1114] bump version

---

.github/workflows/tokamak-public-nightly.yml

make nightly github action fixing push branch
* fix 'main' to 'feature/native-token'

OR-1159 make nightly github action fixing push branch

---

packages/tokamak/contracts/hardhat.config.ts

fix the url field to string type

OR-1165 fix github action error

---

.github/workflows/tokamak-public-nightly.yml
.github/workflows/tokamak-public-release.yml
ops/docker-compose-verifier.yml
ops/docker-compose.yml

- change docker repository
Thank you!

[OR-1702] change docker repository

---

ops/docker/Dockerfile.packages

- update base image
Thank you!

[OR-1702] update base image
