- packages/contracts/deploy/015-L1TonToken.ts
isHardhatNode flag에 따라 L1 토큰 컨트랙트 배포 유무를 결정하도록 변경하였습니다.
- L1 토큰 컨트랙트는 조건문에 따라 hardhat node를 사용할 때만 배포하도록 수정
- rinkeby나 mainet에서는 기존에 배포된 L1 TON contract를 사용
> [OR-251] change deployment logic of l1 token contract

- .github/workflows/tokamak-public-nightly.yml
Github Action 은 확인하려면 머지해서 넣어야지만 가능해서 여러가지로 불편하네요.
이제 마지막 수정일듯합니다.
> [OR-344] Fix nightly build for batch-submitter-service

- .github/workflows/tokamak-public-release.yml
실수했네요.
release시 tokamak-message-relayer가 실제로 만들어지지 않고 있었습니다.
버그 수정합니다~
> [OR-370] Fix ci target for tokamak-message-relayer

- packages/sdk/src/cross-chain-messenger.ts
- packages/tokamak/contracts/package.json
- packages/tokamak/message-relayer/.env.example
- packages/tokamak/message-relayer/package.json
- packages/tokamak/message-relayer/src/service.ts
- yarn.lock
fast_relayer 서비스의 초기화 함수를 구현
- fast withdraw와 batch relay를 위한 옵션 추가
- CrossChainMessenger class 생성 시 L1CrossDomainMessengerFast 컨트랙트 객체 추가
- FAST_RELAYER 환경 변수 적용
log를 확인하여 초기화에서 fast_relayer 서비스의 옵션이 잘 세팅되었는지 체크
```bash
git checkout OR-460_make-initialization
yarn && yarn build
cd ops && docker-compose up -d
docker logs -f <CONTAINER_ID_MESSAGE_RELAYER_FAST>
docker logs -f <CONTAINER_ID_MESSAGE_RELAYER>
```
```bash
cd packages/tokamak/message-relayer
cp .env.example .env
npm run start
```
https://onther.atlassian.net/browse/OR-460
> OR-460 make initialization

- ops/docker/Dockerfile.packages
inactivate bedrock build in docker. this might be used in later, so didn't completely remove it.
> OR-506 inactivate bedrock build in docker

- packages/contracts/deploy/016-fund-accounts.ts
integration-tests의 fee-payment.spec.ts 에서 트랜잭션 오류가 발생하여 deployer가 L2Wallet에 deposit하는 수량을 10 eth → 20 eth로 수정했습니다.
JIRA: https://onther.atlassian.net/browse/OR-523
> [OR-523] funding amount changed to 20 ETH

- .github/workflows/tokamak-public-nightly.yml
- .github/workflows/tokamak-public-release.yml
github action에서 infra 쪽에 tag 업데이트하는 workflow 추가했습니다.
nightly는 테스트 했는데 release는 아직 새로운 release가 없어서 테스트는 못했습니다.
다음에 release할때에 상황을 봐야할 것 같아요.
> Or 509 auto update images

- integration-tests/test/batch-relayer-fast.spec.ts
- ops/docker-compose.yml
- ops/docker/Dockerfile.packages
- packages/sdk/src/cross-chain-messenger.ts
기존 relayer의 서비스 이름 (fast relayer)은 혼동을 줄 수 있어 batch-relay기능을 직관적으로 나타내는 batch-relayer / batch-relayer-fast로 서비스 이름을 변경합니다.
https://onther.atlassian.net/browse/OR-574
> [OR-574] rename the relayer service

- packages/data-transport-layer/src/services/l2-ingestion/service.ts
- dtl l2 sync 전에 connection 시도를 20번에서 무제한으로 변경하였습니다.
- 미미한 코드수정이라, 추후 optimism repo 업데이트 시에도 conflict 가 생기지 않을 것으로 추측되어 package 를 바로 업데이트 하였습니다.
감사드립니다.
> [OR-588] update dtl to not exit

- .github/workflows/tokamak-public-nightly.yml
개발시 Multi platform 빌드된 이미지를 사용하려고 했으나 개발 머신에서 직접 빌드하고 사용하면 되는 부분이라서 삭제합니다.
ci 때문에 바로 머지합니다..
> [OR-600] remove multiplatfor build of github action

- ops/docker-compose.yml
- packages/contracts/docs/ICrossDomainMessenger.md
- packages/contracts/docs/IL1CrossDomainMessenger.md
- packages/contracts/docs/IL2CrossDomainMessenger.md
- packages/contracts/docs/L1CrossDomainMessenger.md
- packages/contracts/docs/L1CrossDomainMessengerFast.md
- packages/contracts/docs/L2CrossDomainMessenger.md
- packages/tokamak/message-relayer/package.json
- packages/tokamak/message-relayer/src/service.ts
- yarn.lock
@tokamak-optimism/message-relayer의 환경 변수/로그를 수정하고 버전을 v0.5.5 -> v0.5.6으로 변경하였습니다.
* FAST_RELAYER > MESSAGE__RELAYER__FAST_RELAYER로 환경 변수 이름 수정
* dotenv 삭제
* 불필요한 log 삭제 및 log 라이브러리 적용
* 패키지 버전 변경: v0.5.5 → v0.5.6
> Or 644 modify env log of relayer

- packages/tokamak/message-relayer/package.json
- packages/tokamak/message-relayer/src/service.ts
Tx를 receipt를 받아오고 찍으면 블록이 생성될때까지 기다리게 되고 오류시 확인할 수가 없기때문에 tx 전송후 바로 찍게했습니다.
> [OR-655] Change position to show tx sent log

- packages/contracts/deploy/017-OVM_L1StandardBridge.deploy.ts
doActions할 경우에 out of gas가 나올때가 있습니다.
이때에는 bytecode를 직접 넣어주어야합니다.
> [OR-695] Add logs for manual deployment

- packages/contracts/hardhat.config.ts
- packages/tokamak/message-relayer/package.json
- packages/tokamak/message-relayer/src/service.ts
**We have found the uncertainty in the logic. But there are no bug.** 
There are two changes for operational convenience.
1. Modify info/debug log to find TXID by dividing relay transaction into request/authorization
2. Add info logs because it should be possible to check when relaying is not possible due to high gas price.
> [OR-671] change log level

- packages/contracts/hardhat.config.ts
I added `titan` network to hardhat.config due to verify contracts on blockexplorer.
> [OR-719] Add titan network to hardhat config

- ops/scripts/batch-submitter.sh
- ops/scripts/relayer.sh
- add l2 health check method because of proxy package.
we are using a proxy for l2 request, but the proxy doesn't permit request without path and body. so I added health check mehod after internal test.
thank you!
> [OR-793] add l2 health check method (not permit request without anything in proxyd)

- .github/workflows/titan-packages-release.yml
- packages/tokamak/sdk/package.json
- yarn.lock
added github action workflow for titan packages
* target branch: main
* determine packages to publish (will be add @tokamak-network/titan-contracts in filter)
* publish packages to npm (if local package version is lower than npm registry, skip the publish the package. so we should bump version after we change code of titan packages)
> [OR-723] github action for titan packages

- .github/workflows/titan-packages-release.yml
changed the conditions under which the github action workflow is triggered **to provide stable packages** to the public npm registry.
- from: push event occurs on main branch
- to: push event occurs that pushes a tag of the form 'release-*'
Thanks to @harryoh
> [OR-873] change trigger of titan npm package ci/cd

- ops/README.md
I noticed a very minor typo while reading through the file.
> Fix minor typo in ops README

- ops/docker/hardhat/Dockerfile
When building with the existing code, the following error occurs.
`@nomicfoundation/ethereumjs-util@9.0.4: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.20.2"`
Fixed node version from 16 to 18.
> Modified ops/docker/hardhat/Dockerfile
